### ISSUE TITLE
I solved this issue

### ISSUE THREAD

**Issue by manupillai308** [Leosocy/EDCC-Palmprint-Recognition#22]
I solved this issue 

> > This is the error I got while running python seytup.py install
> > and also same kind of error on Robustpalmroi
> > Traceback (most recent call last):
> > File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/adapter.py", line 24, in **init**
> > self._lib = ctypes.cdll.LoadLibrary(self.LIB_NAME)
> > File "/home/qwickbit/anaconda3/lib/python3.6/ctypes/**init**.py", line 426, in LoadLibrary
> > return self._dlltype(name)
> > File "/home/qwickbit/anaconda3/lib/python3.6/ctypes/**init**.py", line 348, in **init**
> > self._handle = _dlopen(self._name, mode)
> > OSError: libedcc.so: cannot open shared object file: No such file or directory
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "setup.py", line 10, in
> > import edcc
> > File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/**init**.py", line 31, in
> > adapter = EdccAdapter()
> > File "/home/qwickbit/Desktop/EDCC-Palmprint-Recognition/pypackage/edcc/adapter.py", line 28, in **init**
> > self.LIB_NAME, self.LIB_INSTALLATION_URL
> > OSError: Library [libedcc.so] not found.
> > Please see https://github.com/Leosocy/EDCC-Palmprint-Recognition#install-library
> 
> Do you have `so library` installed?

_Originally posted by @manoharsonwan in https://github.com/Leosocy/EDCC-Palmprint-Recognition/issues/18#issuecomment-504368059_

**Comment by manupillai308** [comment]
The file ```libedcc.so``` is in the directory where you build the project. By simply copying the content from folder ```pypackage```  to  the ```build``` directory and the running 
```python
python setup.py install
```
