### ISSUE TITLE
Library not loaded: @rpath/libopencv_gapi.4.2.dylib

### ISSUE THREAD

**Issue by zhouchaohong1111** [Leosocy/EDCC-Palmprint-Recognition#26]
python3 setup.py install
Traceback (most recent call last):
  File "/Users/zhouchaohong/Documents/PythonProjects/EDCC-Palmprint-Recognition-master/pypackage/edcc/adapter.py", line 24, in __init__
    self._lib = ctypes.cdll.LoadLibrary(self.LIB_NAME)
  File "/opt/anaconda3/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/opt/anaconda3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libedcc.dylib, 6): Library not loaded: @rpath/libopencv_gapi.4.2.dylib
  Referenced from: /usr/local/lib/libedcc.0.2.0.dylib
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    import edcc
  File "/Users/zhouchaohong/Documents/PythonProjects/EDCC-Palmprint-Recognition-master/pypackage/edcc/__init__.py", line 31, in <module>
    adapter = EdccAdapter()
  File "/Users/zhouchaohong/Documents/PythonProjects/EDCC-Palmprint-Recognition-master/pypackage/edcc/adapter.py", line 28, in __init__
    self.LIB_NAME, self.LIB_INSTALLATION_URL
OSError: Library [libedcc.dylib] not found.
-------------------
in fact opencv4.2 is installed

**Comment by zhouchaohong1111** [comment]
set dyld path  and solved this issue
```
export DYLD_LIBRARY_PATH=/usr/local/opencv4/lib/:/usr/local/opt/hdf5/lib/
```
